all:
	gcc source/child.c -o bin/child
	gcc source/childfaulter.c -o bin/childfaulter
	gcc source/childmintime.c -o bin/childmintime
	echo "Done compiling"

clean:
	rm -f bin/child
	rm -f bin/childfaulter
	rm -f bin/childmintime
	echo "Done cleaning"